stages:
  - prepare
  - test

yarn:
  stage: prepare
  tags:
    - docker
  image: cookielab/nodejs:8
  script:
    - yarn
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - node_modules
  artifacts:
    name: "$CI_JOB_NAME"
    expire_in: 1 day
    paths:
      - node_modules

lint:
  stage: test
  tags:
    - docker
  dependencies:
    - yarn
  image: cookielab/nodejs:8
  script:
    - bin/lint

flow:
  stage: test
  tags:
    - docker
  dependencies:
    - yarn
  image: cookielab/nodejs:8
  script:
    - bin/flow

test:
  stage: test
  tags:
    - docker
  dependencies:
    - yarn
  services:
  image: cookielab/nodejs:8
  variables:
  script:
    - bin/jest --coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
